const mongoose = require("mongoose");

const paymentSchema = new mongoose.Schema(
  {
    // Link to the order this payment covers
    order: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Order",
      required: true,
    },
    // The restaurant that receives the payment
    restaurant: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Restaurant",
      required: true,
    },
    // The customer who paid
    customer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // ── Payment method ───────────────────────────────────────────────────────
    // "card"  → net banking / debit / credit card form
    // "qr"    → UPI QR code scan
    // "cod"   → cash on delivery (no payment record needed but kept for completeness)
    paymentMethod: {
      type: String,
      enum: ["card", "qr", "cod"],
      required: true,
    },

    // ── Status ───────────────────────────────────────────────────────────────
    // "pending"             → payment initiated but not confirmed
    // "paid"                → confirmed paid
    // "pending_verification"→ QR payment claimed by customer, awaiting owner confirm
    // "failed"              → payment failed
    paymentStatus: {
      type: String,
      enum: ["pending", "paid", "pending_verification", "failed"],
      default: "pending",
    },

    amount: { type: Number, required: true },

    // Masked card details — never store full card number
    cardDetails: {
      cardHolderName: { type: String, default: "" },
      last4Digits:    { type: String, default: "" }, // last 4 of card number
      expiryDate:     { type: String, default: "" }, // MM/YY
    },

    // For QR/UPI payments
    upiId: { type: String, default: "" },

    // Unique transaction reference (generated by us for demo, real gateway provides this)
    transactionId: {
      type: String,
      unique: true,
      sparse: true,
    },

    paymentDate: { type: Date, default: Date.now },
    notes: { type: String, default: "" },
  },
  { timestamps: true }
);

// Auto-generate transactionId before save if not provided
paymentSchema.pre("save", function (next) {
  if (!this.transactionId) {
    const ts   = Date.now().toString(36).toUpperCase();
    const rand = Math.random().toString(36).toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 6);
    this.transactionId = `TXN-${ts}-${rand}`;
  }
  next();
});

module.exports = mongoose.model("Payment", paymentSchema);